%% change this
filename = '2021-02-16 04';

%% dont change this
folder = 'datasets/';
savepath = join([folder, filename]);
save(savepath,'out','p');

format long
copy_paste_excel = [...
h; ...
stoptime; ...
ref_select; ...
strategy_select; ...
p.interval; ...
p.num_reac; ...
p.max_pump_flow; ...
p.pump_res; ...
p.clean_time; ...
p.waste_threshold; ...
p.valve_switch_time; ...
];


